apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argo-demo
spec:
  type: NodePort  # Change the type to NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30000  # Specify a NodePort if you want, or let Kubernetes allocate one automatically
